# версия docker-compose
version: '3.3'

# имена и описания контейнеров, которые должны быть развёрнуты
services:

  db:
    # образ, из которого должен быть запущен контейнер
    image: postgres:13.0-alpine
    restart: always
    # volume и связанная с ним директория в контейнере
    volumes:
      - database_value:/var/lib/postgresql/data/
    # адрес файла, где хранятся переменные окружения
    env_file:
      - ./.env

  backend:
    image: kaydalova/flowerbot:latest
    restart: always
    volumes:
      # Контейнер web будет работать с данными, хранящиеся в томе static_value, 
      # через свою директорию /app/static/
      - static_value:/app/static/
      # Данные, хранящиеся в томе media_value, будут доступны в контейнере web 
      # через директорию /app/media/
      - media_value:/app/media/
    # «зависит от»
    depends_on:
      - db
    env_file:
      - ./.env


  nginx:
    # образ, из которого должен быть запущен контейнер
    image: nginx:1.19.3
    # запросы с внешнего порта 80 перенаправляем на внутренний порт 80
    ports:
      - "80:80"
      - "443:443"  # certbot
    restart: always
    volumes:
      # При сборке скопировать созданный конфиг nginx из исходной директории 
      # в контейнер и сохранить его в директорию /etc/nginx/conf.d/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # Контейнер nginx будет работать с данными, хранящиеся в томе static_value, 
      # через свою директорию /var/html/static/
      - static_value:/var/html/static/
      # Данные, хранящиеся в томе media_value, будут доступны в контейнере nginx
      # через директорию /var/html/media/
      - media_value:/var/html/media/
      # certbot
      - ./certbot/www:/var/www/certbot/:ro

    depends_on:
      - backend

  # certbot
  certbot:
    container_name: service_certbot
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
  


volumes:
  static_value:
  media_value:
  database_value: