# Generated by Django 2.2.19 on 2023-03-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, unique=True, verbose_name='Название растения')),
                ('type', models.CharField(max_length=400, verbose_name='Тип растения')),
                ('temperature', models.CharField(max_length=100, verbose_name='Оптимальная температура')),
                ('light', models.CharField(max_length=1000, verbose_name='Световой режим')),
                ('watering', models.CharField(max_length=1000, verbose_name='Режим полива')),
            ],
        ),
    ]
