# Generated by Django 2.2.19 on 2023-03-17 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0002_auto_20230317_0945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flower',
            options={'ordering': ('name',), 'verbose_name': 'Каталог растений', 'verbose_name_plural': 'Каталог растений'},
        ),
    ]
