# Generated by Django 2.2.19 on 2023-03-20 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0003_auto_20230317_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='feeding_int',
            field=models.SmallIntegerField(default=1, verbose_name='Подкормка для бота, номер месяца'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flower',
            name='pot',
            field=models.CharField(default=1, max_length=1000, verbose_name='Горшочек'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flower',
            name='sprinkle_int',
            field=models.SmallIntegerField(default=1, verbose_name='Частота опрыскиваний для бота'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flower',
            name='watering_int',
            field=models.SmallIntegerField(default=1, verbose_name='Частота полива для бота'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersflower',
            name='chat_id',
            field=models.CharField(default=1, max_length=9, verbose_name='Телеграм chat id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flower',
            name='watering',
            field=models.CharField(max_length=1000, verbose_name='Режим полива, подкормки и опрыскивания'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.SmallIntegerField(verbose_name='День недели от 0 до 6')),
                ('time', models.TimeField(verbose_name='Время полива')),
                ('action', models.SmallIntegerField(verbose_name='1 - полить, 0 - побрызгать, 2 - подкормить')),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowers.UsersFlower', verbose_name='Цветочек')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
                'ordering': ('day',),
            },
        ),
    ]
