# Generated by Django 2.2.16 on 2023-03-31 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0006_auto_20230331_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='flowers/images/', verbose_name='Фотография растения'),
        ),
    ]
