# Generated by Django 2.2.16 on 2023-04-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0007_flower_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='pat_friendly',
            field=models.CharField(default=1, max_length=1000, verbose_name='Пэт-френдли'),
            preserve_default=False,
        ),
    ]
