# Generated by Django 2.2.16 on 2023-04-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0008_flower_pat_friendly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersflower',
            name='notification',
            field=models.BooleanField(default=False, verbose_name='Оповещения в телеграм'),
        ),
    ]
