# Generated by Django 2.2.16 on 2023-04-24 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0013_auto_20230414_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flower',
            name='feeding_int',
        ),
        migrations.RemoveField(
            model_name='flower',
            name='sprinkle_int',
        ),
        migrations.RemoveField(
            model_name='flower',
            name='watering_int',
        ),
        migrations.AlterField(
            model_name='usersflower',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
    ]
