# Generated by Django 2.2.16 on 2023-07-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0015_auto_20230426_1734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersflower',
            options={'verbose_name': 'Цветочек', 'verbose_name_plural': 'Цветочки'},
        ),
        migrations.AddField(
            model_name='schedule',
            name='once_every_three_days',
            field=models.BooleanField(default=False),
        ),
    ]
