# Generated by Django 2.2.19 on 2023-03-20 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0004_auto_20230320_0438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersflower',
            name='chat_id',
        ),
        migrations.AddField(
            model_name='usersflower',
            name='notification',
            field=models.BooleanField(default=1, verbose_name='Оповещения в теоеграм'),
            preserve_default=False,
        ),
    ]
