export const bazeUrl = "http://62.113.100.196/api";

export const ERROR_MESSAGE = {
  DATA_RECEIVE_ERROR: 'Во время запроса произошла ошибка. Возможно, проблема с соединением или сервер недоступен. Подождите немного и попробуйте ещё раз.',
  SIGNUP_ERROR: 'При обработке данных что-то пошло не так. Проверьте введенные данные и попробуйте еще раз.',
  AUTH_ERROR: 'Что-то не так с авторизацией. Пожалуйста, войдите в свой профиль.',
  SOMETHING_WRONG: 'Ошибка по умолчанию.',
  SAME_EMAIL: 'Такой email уже существует.'
};

export const URL_PATTERN = /^:?https?:\/\/(www\.)?[a-zA-Z\d-]+\.[\w\d\-.~:/?#[\]@!$&'()*+,;=]{2,}#?$/;

export const GET_PLANTS = 'GET_PLANTS';
export const GET_PLANTS1 = 'GET_PLANTS1';
export const GET_PLANTS_FAILED = 'GET_PLANTS_FAILED';
export const GET_PLANTS_SUCCESS = 'GET_PLANTS_SUCCESS';
export const SEND_USER_FLOWERS_REQUEST = 'SEND_USER_FLOWERS_REQUEST';
export const SEND_USER_FLOWERS_REQUEST_FAILED = 'SEND_USER_FLOWERS_REQUEST_FAILED';
export const SEND_USER_FLOWERS_REQUEST_SUCCESS = 'SEND_USER_FLOWERS_REQUEST_SUCCESS';
export const REMOVE_USER_FLOWERS = 'REMOVE_USER_FLOWERS';
export const SET_PLANT = 'SET_PLANT';
export const CLEAR_CURRENT_PLANT = 'CLEAR_CURRENT_PLANT';
export const SET_FLOWER = 'SET_FLOWER';
export const CLEAR_CURRENT_FLOWER = 'CLEAR_CURRENT_FLOWER';
export const SEND_EMAIL = 'SEND_EMAIL';
export const SEND_EMAIL_FAILED = 'SEND_EMAIL_FAILED';
export const SEND_EMAIL_SUCCESS = 'SEND_EMAIL_SUCCESS';
export const REMOVE_EMAIL = 'REMOVE_EMAIL';
export const SEND_REGISTER_DATA = 'SEND_REGISTER_DATA';
export const SEND_REGISTER_DATA_FAILED = 'SEND_REGISTER_DATA_FAILED';
export const SEND_REGISTER_DATA_SUCCESS = 'SEND_REGISTER_DATA_SUCCESS';
export const REMOVE_REGISTER_DATA = 'REMOVE_REGISTER_DATA';
export const SEND_LOGIN_DATA = 'SEND_LOGIN_DATA';
export const SEND_LOGIN_DATA_FAILED = 'SEND_LOGIN_DATA_FAILED';
export const SEND_LOGIN_DATA_SUCCESS = 'SEND_LOGIN_DATA_SUCCESS';
export const REMOVE_LOGIN_DATA = 'REMOVE_LOGIN_DATA';
export const SEND_PASSWORD = 'SEND_PASSWORD';
export const SEND_PASSWORD_FAILED = 'SEND_PASSWORD_FAILED';
export const SEND_PASSWORD_SUCCESS = 'SEND_PASSWORD_SUCCESS';
export const REMOVE_PASSWORD = 'REMOVE_PASSWORD';
export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_REQUEST_FAILED = 'GET_USER_REQUEST_FAILED';
export const GET_USER_REQUEST_FAILED_TOKEN = 'GET_USER_REQUEST_FAILED_TOKEN';
export const GET_USER_REQUEST_SUCCESS = 'GET_USER_REQUEST_SUCCESS';
export const REMOVE_USER_DATA = 'REMOVE_USER_DATA';
export const SEND_UPDATED_USER_REQUEST = 'SEND_UPDATED_USER_REQUEST';
export const SEND_USER_REQUEST_FAILED = 'SEND_USER_REQUEST_FAILED';
export const SEND_USER_REQUEST_SUCCESS = 'SEND_USER_REQUEST_SUCCESS';
export const SEND_LOGOUT_REQUEST = 'SEND_LOGOUT_USER_REQUEST';
export const SEND_LOGOUT_REQUEST_FAILED = 'SEND_LOGOUT_REQUEST_FAILED';
export const SEND_LOGOUT_REQUEST_SUCCESS = 'SEND_LOGOUT_REQUEST_SUCCESS';
export const REMOVE_LOGOUT_DATA = 'REMOVE_LOGOUT_DATA';
export const SEND_REFRESH_TOKEN_REQUEST = 'SEND_REFRESH_TOKEN_REQUEST';
export const SEND_REFRESH_TOKEN_REQUEST_FAILED = 'SEND_REFRESH_TOKEN_REQUEST_FAILED';
export const SEND_REFRESH_TOKEN_REQUEST_SUCCESS = 'SEND_REFRESH_TOKEN_REQUEST_SUCCESS';
export const REMOVE_REFRESH_TOKEN_DATA = 'REMOVE_REFRESH_TOKEN_DATA';
export const SET_LOCATION = 'SET_LOCATION';
export const ON_CLICK = 'ON_CLICK';
export const REMOVE_ON_CLICK = 'REMOVE_ON_CLICK';
export const REMOVE_LOCATIONS = 'REMOVE_LOCATIONS';
export const ADD_FLOWER = 'ADD_FLOWER';
export const ADD_FLOWER_FAILED = 'ADD_FLOWER_FAILED';
export const ADD_FLOWER_SUCCESS = 'ADD_FLOWER_SUCCESS';
export const EDIT_FLOWER = 'EDIT_FLOWER';
export const EDIT_FLOWER_FAILED = 'EDIT_FLOWER_FAILED';
export const EDIT_FLOWER_SUCCESS = 'EDIT_FLOWER_SUCCESS';
export const DELETE_FLOWER = 'DELETE_FLOWER';
export const DELETE_FLOWER_FAILED = 'DELETE_FLOWER_FAILED';
export const DELETE_FLOWER_SUCCESS = 'DELETE_FLOWER_SUCCESS';
export const GET_MY_FLOWERS = 'GET_MY_FLOWERS';
export const GET_MY_FLOWERS1 = 'GET_MY_FLOWERS1';
export const GET_MY_FLOWERS_FAILED = 'GET_MY_FLOWERS_FAILED';
export const GET_MY_FLOWERS_SUCCESS = 'GET_MY_FLOWERS_SUCCESS';
